apiVersion: v1
kind: Service
metadata:
  name: {{ template "integration-manager.aggregator.fullname" . }}
  {{- if .Values.aggregator.service.annotations }}
  annotations:
    {{ .Values.aggregator.service.annotations  | toYaml | indent 4 | trim }}
  {{- end }}
  labels:
    app: integration-manager
    component: aggregator
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: integration-manager
    component: aggregator
    release: {{ .Release.Name }}
  type: "{{ .Values.aggregator.service.type }}"