{{- if .Values.aggregatorProcessor.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.aggregator-processor.fullname" . }}
  labels:
    app: integration-manager
    component: aggregator-processor
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: aggregator-processor
      release: {{ .Release.Name }}
  {{ toYaml .Values.aggregatorProcessor.pdb | indent 2 | trim }}
{{- end }}
