{{- if .Values.aggregator.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.aggregator.fullname" . }}
  labels:
    app: integration-manager
    component: aggregator
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: aggregator
      release: {{ .Release.Name }}
  {{ toYaml .Values.aggregator.pdb | indent 2 | trim }}
{{- end }}
