apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "integration-manager.authorization.fullname" . }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
data:
  application.properties: |
    #authorization specific properties
    {{- if .Values.authorization.extraConfig }}
    {{ .Values.authorization.extraConfig | indent 4 | trim }}
    {{- end }}
