{{- if .Values.authorizationService.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.authorizationService.fullname" . }}
  labels:
    app: integration-manager
    component: authorizationService
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: authorizationService
      release: {{ .Release.Name }}
  {{ toYaml .Values.authorizationService.pdb | indent 2 | trim }}
{{- end }}
