apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "integration-manager.base.fullname" . }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
data:
  application.properties: |
    #integration-manager-base specific properties
    engine.iniFilePath=${sharedDataPath}/conf/cosmos.ini
    {{- if .Values.agent.baseUrl }}
    agent.base-url={{ .Values.agent.baseUrl }}
    {{- end }}
    {{- if .Values.agent.windowsEngine }}
    agent.windows-engine={{ .Values.agent.windowsEngine }}
    {{- end }}
    {{- if .Values.agent.linuxEngine }}
    agent.linux-engine={{ .Values.agent.linuxEngine }}
    {{- end }}
    {{- if .Values.integrationManagerBase.extraConfig }}
    {{ .Values.integrationManagerBase.extraConfig | indent 4 | trim }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "integration-manager.base.fullname" . }}-dest-licenses
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.integrationManagerBase.license }}
  dc11.slc: |
    {{ .Values.integrationManagerBase.license | toString | indent 4 | trim }}
    {{- end }}
    {{- if .Values.integrationManagerBase.dflicense }}
  df6.slc: |
    {{ .Values.integrationManagerBase.dflicense | toString | indent 4 | trim }}
    {{- end }}
