apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "integration-manager.design-engine.fullname" . }}
  labels:
    app: integration-manager
    component: design-engine
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.designEngine.replicaCount }}
  revisionHistoryLimit: {{ .Values.designEngine.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: integration-manager
      component: design-engine
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/sharedconfig: {{ include (print $.Template.BasePath "/shared-configmap.yaml") . | sha256sum }}
        checksum/designengineconfig: {{ include (print $.Template.BasePath "/design-engine-configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.jobExecution.podAnnotations }}
        {{ .Values.jobExecution.podAnnotations | toYaml | indent 8 | trim }}
        {{- end }}
      labels:
        app: integration-manager
        component: design-engine
        chart: {{ template "integration-manager.chart" . }}
        release: {{ .Release.Name }}
        {{- if .Values.designEngine.extraLabels }}
        {{ .Values.designEngine.extraLabels | toYaml | indent 8 | trim }}
        {{- end }}
    spec:
      {{- if .Values.designEngine.affinity }}
      affinity:
        {{ .Values.designEngine.affinity | toYaml | indent 8 | trim }}
      {{- end }}
      serviceAccountName: {{ template "integration-manager.fullname" . }}
      {{- if .Values.designEngine.nodeSelector }}
      nodeSelector:
        {{ .Values.designEngine.nodeSelector | toYaml | indent 8 | trim  }}
      {{- end }}
      {{- if .Values.designEngine.extraInitContainers }}
      initContainers:
        {{ tpl .Values.designEngine.extraInitContainers . | indent 6 | trim }}
      {{- end }}
      containers:
      - name: design-engine
        image: {{ .Values.designEngine.image }}
        imagePullPolicy: {{ .Values.designEngine.pullPolicy }}
        env:
        - name: IM_SHARED_CONFIGMAP_NAME
          value: {{ printf "%s-shared" (include "integration-manager.fullname" .) }}
        - name: DESIGN_ENGINE_CONFIGMAP_NAME
          value: {{ template "integration-manager.design-engine.fullname" . }}
        {{- if .Values.repository.awsCreateEnvVar }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key
              {{- if .Values.existingSecret }}
              name: {{ .Values.existingSecret }}
              {{- else }}
              name: {{ template "integration-manager.fullname" . }}
              {{- end }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-key
              {{- if .Values.existingSecret }}
              name: {{ .Values.existingSecret }}
              {{- else }}
              name: {{ template "integration-manager.fullname" . }}
              {{- end }}
        {{- end }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secrets
        {{- if .Values.existingRabbitSecret }}
        - name: amqp-secret-volume
          readOnly: true
          mountPath: /etc/secrets/amqp
        {{- end }}
        readinessProbe:
          {{ .Values.designEngine.readinessProbe | toYaml | indent 10 | trim }}
        livenessProbe:
          {{ .Values.designEngine.livenessProbe | toYaml | indent 10 | trim }}
        {{- if .Values.designEngine.resources }}
        resources:
          {{ .Values.designEngine.resources | toYaml | indent 10 | trim }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
      - name: secret-volume
        secret:
          {{- if .Values.existingSecret }}
          secretName: {{ .Values.existingSecret }}
          {{- else }}
          secretName: {{ template "integration-manager.fullname" . }}
          {{- end }}
      {{- if .Values.existingRabbitSecret }}
      - name: amqp-secret-volume
        secret:
          secretName: {{ .Values.existingRabbitSecret }}
          items:
          - key: rabbitmq-username
            path: rabbitmq-username
          - key: rabbitmq-password
            path: rabbitmq-password
      {{- end }}
