{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "integration-manager.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ .Values.ingress.annotations  | toYaml | indent 4 | trim }}
  {{- end }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecret }}
      {{- if .Values.ingress.hostName }}
      hosts:
        - {{ .Values.ingress.hostName }}
      {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostName }}
    - host: {{ .Values.ingress.hostName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/login.*)
          {{- else }}
          path: /api/login
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/logout.*)
          {{- else }}
          path: /api/logout
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(login.*)
          {{- else }}
          path: /login
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /(oauth2.*)
          {{- else }}
          path: /oauth2
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/access.*)
          {{- else }}
          path: /api/access
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/token-exchange.*)
          {{- else }}
          path: /api/token-exchange
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/google-token-exchange.*)
          {{- else }}
          path: /api/google-token-exchange
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/okta-token-exchange.*)
          {{- else }}
          path: /api/okta-token-exchange
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/account.*)
          {{- else }}
          path: /api/account
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/user.*)
          {{- else }}
          path: /api/user
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/license.*)
          {{- else }}
          path: /api/license
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobdestinations.*)
          {{- else }}
          path: /api/jobdestinations
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/agentdestinations.*)
          {{- else }}
          path: /api/agentdestinations
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/users.*)
          {{- else }}
          path: /api/users
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/groups.*)
          {{- else }}
          path: /api/groups
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobtemplates.*)
          {{- else }}
          path: /api/jobtemplates
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfigs.*)
          {{- else }}
          path: /api/jobconfigs
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/fileloader.*)
          {{- else }}
          path: /api/fileloader
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(oauth.*)
          {{- else }}
          path: /oauth
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfig-aliases.*)
          {{- else }}
          path: /api/jobconfig-aliases
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.aggregator.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/aggregators.*)
          {{- else }}
          path: /api/aggregators
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.job-execution.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/listener.*)
          {{- else }}
          path: /api/listener
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.job-execution.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfigs\/.*\/jobs.*)
          {{- else }}
          path: /api/jobconfigs/.*/jobs
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.job-execution.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfigs\/.*\/jobmessage.*)
          {{- else }}
          path: /api/jobconfigs/.*/jobmessage
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.job-execution.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfigs\/.*\/listener.*)
          {{- else }}
          path: /api/jobconfigs/.*/listener
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/device.*)
          {{- else }}
          path: /api/device/*
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/devices.*)
          {{- else }}
          path: /api/devices/*
          {{- end }}
          pathType: ImplementationSpecific
        {{- if .Values.jobLogStreaming.enabled }}
        - backend:
            service:
              name: {{ template "integration-manager.job-log-streaming.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/api/jobs/([^\/]+\/logevents.*)
          {{- else }}
          path: /api/jobs/([^\/]+\/logevents.*)
          {{- end }}
          pathType: ImplementationSpecific
        {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.job-execution.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobs.*)
          {{- else }}
          path: /api/jobs
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/subscriptions.*)
          {{- else }}
          path: /api/subscriptions
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/agents.*)
          {{- else }}
          path: /api/agents
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.job-results-processor.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobs\/events.*)
          {{- else }}
          path: /api/jobs/events
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(\.well-known\/openid-configuration.*)
          {{- else }}
          path: /.well-known/openid-configuration
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(apidocs.*)
          {{- else }}
          path: /apidocs
          {{- end }}
          pathType: ImplementationSpecific
          {{- if .Values.ingress.pathVersionPrefix }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          path: /(apidocs.*)
          pathType: ImplementationSpecific
          {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(ui.*)
          {{- else }}
          path: /ui
          {{- end }}
          pathType: ImplementationSpecific
          {{- if .Values.ingress.pathVersionPrefix }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          path: /(ui.*)
          pathType: ImplementationSpecific
          {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(dx.*)
          {{- else }}
          path: /dx
          {{- end }}
          pathType: ImplementationSpecific
          {{- if .Values.ingress.pathVersionPrefix }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          path: /(dx.*)
          pathType: ImplementationSpecific
          {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(ui.*)
          {{- else }}
          path: /ui
          {{- end }}
          pathType: ImplementationSpecific
          {{- if .Values.ingress.pathVersionPrefix }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          path: /(ui.*)
          pathType: ImplementationSpecific
          {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(info.*)
          {{- else }}
          path: /info
          {{- end }}
          pathType: ImplementationSpecific
          {{- if .Values.ingress.pathVersionPrefix }}
        - backend:
            service:
              name: {{ template "integration-manager.static-content.fullname" . }}
              port:
                number: 80
          path: /(info.*)
          pathType: ImplementationSpecific
          {{- end }}
        - backend:
            service:
              name: {{ template "integration-manager.job-scheduler.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/jobconfigs\/.*\/schedule.*)
          {{- else }}
          path: /api/jobconfigs/.*/schedule
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/downloads.*)
          {{- else }}
          path: /api/downloads
          {{- end }}
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ template "integration-manager.base.fullname" . }}
              port:
                number: 8080
          {{- if .Values.ingress.pathVersionPrefix }}
          path: /{{ .Values.ingress.pathVersionPrefix }}/(api\/product.*)
          {{- else }}
          path: /api/product
          {{- end }}
          pathType: ImplementationSpecific
        # Expose this when ready
#        - backend:
#            serviceName: {{ template "integration-manager.base.fullname" . }}
#            servicePort: 8080
#          path: /api/clientdetails
    {{- end }}
