apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "integration-manager.job-results-processor.fullname" . }}
  labels:
    app: integration-manager
    component: job-results-processor
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.jobResultsProcessor.replicaCount }}
  revisionHistoryLimit: {{ .Values.jobResultsProcessor.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: integration-manager
      component: job-results-processor
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/sharedconfig: {{ include (print $.Template.BasePath "/shared-configmap.yaml") . | sha256sum }}
        checksum/jobresprossconfig: {{ include (print $.Template.BasePath "/job-results-processor-configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.jobResultsProcessor.podAnnotations }}
        {{ .Values.jobResultsProcessor.podAnnotations | toYaml | indent 8 | trim }}
        {{- end }}
      labels:
        app: integration-manager
        component: job-results-processor
        chart: {{ template "integration-manager.chart" . }}
        release: {{ .Release.Name }}
        {{- if .Values.jobResultsProcessor.extraLabels }}
        {{ .Values.jobResultsProcessor.extraLabels | toYaml | indent 8 | trim }}
        {{- end }}
    spec:
      {{- if .Values.jobResultsProcessor.affinity }}
      affinity:
        {{ .Values.jobResultsProcessor.affinity | toYaml | indent 8 | trim }}
      {{- end }}
      serviceAccountName: {{ template "integration-manager.fullname" . }}
      {{- if .Values.jobResultsProcessor.nodeSelector }}
      nodeSelector:
        {{ .Values.jobResultsProcessor.nodeSelector | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.jobResultsProcessor.extraInitContainers }}
      initContainers:
        {{ tpl .Values.jobResultsProcessor.extraInitContainers . | indent 6 | trim }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.jobResultsProcessor.podSecurityContext | nindent 8 }}
      containers:
      - name: job-results-processor
        image: {{ .Values.jobResultsProcessor.image }}
        imagePullPolicy: {{ .Values.jobResultsProcessor.pullPolicy }}
        securityContext:
          {{- toYaml .Values.jobResultsProcessor.securityContext | nindent 10 }}
        env:
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.jobResultsProcessor.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: im-shared-volume
          readOnly: true
          mountPath: /etc/config/shared.properties
          subPath: application.properties
        - name: job-results-volume
          readOnly: true
          mountPath: /etc/config/application.properties
          subPath: application.properties
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secrets
        {{- if .Values.existingRabbitSecret }}
        - name: amqp-secret-volume
          readOnly: true
          mountPath: /etc/secrets/amqp
        {{- end }}
        readinessProbe:
          {{ .Values.jobResultsProcessor.readinessProbe | toYaml | indent 10 | trim }}
        livenessProbe:
          {{ .Values.jobResultsProcessor.livenessProbe | toYaml | indent 10 | trim }}
        {{- if .Values.jobResultsProcessor.resources }}
        resources:
          {{ .Values.jobResultsProcessor.resources | toYaml | indent 10 | trim }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
      - name: im-shared-volume
        configMap:
          name: {{ template "integration-manager.fullname" . }}-shared
      - name: job-results-volume
        configMap:
          name:  {{ template "integration-manager.job-results-processor.fullname" . }}
      - name: secret-volume
        secret:
          {{- if .Values.existingSecret }}
          secretName: {{ .Values.existingSecret }}
          {{- else }}
          secretName: {{ template "integration-manager.fullname" . }}
          {{- end }}
      {{- if .Values.existingRabbitSecret }}
      - name: amqp-secret-volume
        secret:
          secretName: {{ .Values.existingRabbitSecret }}
          items:
          - key: rabbitmq-username
            path: rabbitmq-username
          - key: rabbitmq-password
            path: rabbitmq-password
      {{- end }}
