{{- if .Values.jobScheduler.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.job-scheduler.fullname" . }}
  labels:
    app: integration-manager
    component: job-scheduler
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: job-scheduler
      release: {{ .Release.Name }}
  {{ toYaml .Values.jobScheduler.pdb | indent 2 | trim }}
  {{- end }}
