{{- if .Values.jobLogStreaming.enabled }}
  {{- if .Values.jobLogStreaming.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.job-log-streaming.fullname" . }}
  labels:
    app: integration-manager
    component: job-log-streaming
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: job-log-streaming
      release: {{ .Release.Name }}
  {{ toYaml .Values.jobLogStreaming.pdb | indent 2 | trim }}
  {{- end }}
{{- end }}
