{{- if .Values.jobSocketExecutor.enabled }}
  {{- if .Values.jobSocketExecutor.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.job-socket-executor.fullname" . }}
  labels:
    app: integration-manager
    component: job-socket-executor
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: job-socket-executor
      release: {{ .Release.Name }}
  {{ toYaml .Values.jobSocketExecutor.pdb | indent 2 | trim }}
  {{- end }}
{{- end }}
