kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "integration-manager.fullname" . }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
