kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "integration-manager.fullname" . }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-configmap-reader
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-secret-reader
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-pod-reader
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-read-configmaps
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "integration-manager.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "integration-manager.fullname" . }}-configmap-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-read-secrets
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "integration-manager.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "integration-manager.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integration-manager.fullname" . }}-read-pods
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "integration-manager.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "integration-manager.fullname" . }}-pod-reader
  apiGroup: rbac.authorization.k8s.io