{{- if not .Values.existingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "integration-manager.fullname" . }}
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if not .Values.existingRabbitSecret }}
  rabbitmq-host: {{ (toString .Values.amqp.host) | b64enc }}
  rabbitmq-username: {{ (toString .Values.amqp.username) | b64enc }}
  rabbitmq-password: {{ (toString .Values.amqp.password) | b64enc }}
  {{- end }}

  {{- if .Values.amqp.sslKeyStorePassword }}
  queue.ssl.key-store-password: {{ (toString .Values.amqp.sslKeyStorePassword) | b64enc }}
  {{- end }}
  {{- if .Values.datasource.password }}
  spring.datasource.password: {{ (toString .Values.datasource.password) | b64enc }}
  {{- end }}
  {{- if .Values.datasource.username }}
  spring.datasource.username: {{ (toString .Values.datasource.username) | b64enc }}
  {{- end }}
  {{- if .Values.notification.springMailPassword }}
  spring.mail.password: {{ (toString .Values.notification.springMailPassword) | b64enc }}
  {{- end }}
  {{- if .Values.notification.springMailUsername }}
  spring.mail.username: {{ (toString .Values.notification.springMailUsername) | b64enc }}
  {{- end }}
  {{- if .Values.encryption.keyStore }}
  dbsecurity.keystore: {{ .Values.encryption.keyStore }}
  {{- end }}
  {{- if .Values.encryption.keyStorePassword }}
  encryption.key-store-password: {{ (toString .Values.encryption.keyStorePassword) | b64enc }}
  {{- end }}
  {{- if .Values.jms.password }}
  spring.jpa.properties.eclipselink.cache.coordination.jndi.user: {{ (toString .Values.jms.password) | b64enc }}
  {{- end }}
  {{- if .Values.jms.username }}
  spring.jpa.properties.eclipselink.cache.coordination.jndi.password: {{ (toString .Values.jms.username) | b64enc }}
  {{- end }}
  {{- if .Values.repository.awsAccessKeyId }}
  aws-access-key: {{ (toString .Values.repository.awsAccessKeyId) | b64enc }}
  {{- end }}
  {{- if .Values.repository.awsSecretAccessKey }}
  aws-secret-key: {{ (toString .Values.repository.awsSecretAccessKey) | b64enc }}
  {{- end }}
{{- end }}
