apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "integration-manager.fullname" . }}-shared
  labels:
    app: integration-manager
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
data:
 {{- if .Values.cache.enable }}
  jndi.properties: |
    java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory
    java.naming.provider.url=tcp://{{ .Values.jms.host }}:{{ .Values.jms.port }}
    topic.EclipseLinkCacheTopic=EclipseLinkCacheTopic
 {{- end }}
  application.properties: |
    im.base-url={{ .Values.imBaseUrl }}
    job.destinationId={{ .Values.destinationId }}
    job.history.max-age=90
    job.history.max-job-count=1000
    job.results.queue-name={{ .Values.resultsQueue }}

    #Datasource
    spring.datasource.platform=mysql
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.url={{ .Values.datasource.url }}
    spring.datasource.hikari.maximum-pool-size={{ .Values.datasource.maximumPoolSize }}
    spring.datasource.hikari.minimum-idle={{ .Values.datasource.minimumIdle }}

    #AMQP
    queue.host={{ default "none" .Values.amqp.host }}
    queue.port={{ .Values.amqp.port }}
    # This is a hack to map existing secrets, rabbitmq-username & rabbitmq-password, to our custom queue properties
    queue.username=${rabbitmq-username}
    queue.password=${rabbitmq-password}
    queue.ssl.enabled={{ .Values.amqp.sslEnabled }}
    queue.management-url={{ default "none" .Values.amqp.managementUrl }}
    {{- if .Values.amqp.sslKeyStore }}
    queue.ssl.key-store={{ .Values.amqp.sslKeyStore }}
    {{- end}}
    queue.ssl.key-store-type={{ .Values.amqp.sslKeyStoreType }}
    queue.ssl.protocol={{ .Values.amqp.sslProtocol }}
    {{- if .Values.amqp.externalHost }}
    queue.external.host={{ default "none" .Values.amqp.externalHost }}
    {{- end }}
    {{- if .Values.amqp.externalPort }}
    queue.external.port={{ .Values.amqp.externalPort }}
    {{- end }}
    {{- if .Values.amqp.externalSslEnabled }}
    queue.external.ssl.enabled={{ default false .Values.amqp.externalSslEnabled }}
    {{- end }}
    queue.amqp.embedded=false
    queue.amqp.enabled=true
    worker.embedded=false

    #Files
    {{- if .Values.repository.storageType }}
    repository.storage-type={{ .Values.repository.storageType }}
    {{- end }}
    {{- if .Values.repository.sourceBucket }}
    repository.source-bucket={{ .Values.repository.sourceBucket }}
    {{- end }}
    {{- if .Values.repository.sourcePrefix }}
    repository.source-prefix={{ .Values.repository.sourcePrefix }}
    {{- else }}
    repository.source-prefix=
    {{- end }}
    {{- if .Values.repository.targetBucket }}
    repository.target-bucket={{ .Values.repository.targetBucket }}
    {{- end }}
    {{- if .Values.repository.targetPrefix }}
    repository.target-prefix={{ .Values.repository.targetPrefix }}
    {{- else }}
    repository.target-prefix=
    {{- end }}
    {{- if .Values.repository.accountDir }}
    repository.account-dir={{ .Values.repository.accountDir }}
    {{- end }}
    {{- if .Values.repository.userDir }}
    repository.user-dir={{ .Values.repository.userDir }}
    {{- end }}
    {{- if .Values.repository.jobTemplateDir }}
    repository.jobtemplate-dir={{ .Values.repository.jobTemplateDir }}
    {{- end }}
    {{- if .Values.repository.jobConfigDir }}
    repository.jobconfig-dir={{ .Values.repository.jobConfigDir }}
    {{- end }}
    {{- if .Values.repository.awsServiceEndpoint }}
    repository.aws.service-endpoint={{ .Values.repository.awsServiceEndpoint }}
    {{- end }}
    {{- if .Values.repository.awsSigningRegion }}
    repository.aws.signing-region={{ .Values.repository.awsSigningRegion }}
    {{- end }}
    {{- if .Values.repository.azureConnectString }}
    repository.azure.connect-string={{ .Values.repository.azureConnectString }}
    {{- end }}
    {{- if .Values.repository.nestedJobStorage }}
    repository.nested-job-storage={{ .Values.repository.nestedJobStorage }}
    {{- end }}

    #MultipartFiles
    spring.servlet.multipart.location=/tmp

    # Notification Service
    notification.enabled={{ .Values.notification.enabled }}
    {{- if .Values.notification.enabled }}
    notification.mailFrom={{  .Values.notification.mailFrom }}
    notification.mailTo={{  .Values.notification.mailTo }}
    {{- end }}

    # Outbound Email Configuration
    spring.mail.host={{ .Values.notification.springMailHost }}
    spring.mail.properties.mail.transport.protocol={{ .Values.notification.springMailProtocol }}
    spring.mail.properties.mail.smtp.port={{ .Values.notification.springMailPort }}
    spring.mail.properties.mail.smtp.auth={{ .Values.notification.springMailAuth }}
    spring.mail.properties.mail.smtp.starttls.enable={{ .Values.notification.springMailTLSEnable }}
    spring.mail.properties.mail.smtp.starttls.required={{ .Values.notification.springMailTLSRequired }}

    # Encryption
    encryption.enabled={{ .Values.encryption.enabled }}
    {{- if .Values.encryption.enabled }}
    encryption.password-encoder-type={{ .Values.encryption.passwordEncoderType }}
    encryption.key-store=/etc/secrets/dbsecurity.keystore
    encryption.certificate-name={{ .Values.encryption.certificateName }}
    {{- end }}

    {{- if .Values.cache.enable }}

    #Coordinated Caching
    spring.jpa.properties.eclipselink.cache.shared.default=true
    spring.jpa.properties.eclipselink.cache.coordination.protocol=jms
    spring.jpa.properties.eclipselink.cache.coordination.jms.host=tcp://{{ .Values.jms.host }}:{{ .Values.jms.port }}
    spring.jpa.properties.eclipselink.cache.coordination.jms.factory=TopicConnectionFactory
    spring.jpa.properties.eclipselink.cache.coordination.jms.topic=EclipseLinkCacheTopic
    {{- else }}
    spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
    {{- end }}

    #Quartz Scheduler Configuration
    spring.quartz.scheduler-factory.startup-delay=29

    spring.main.allow-bean-definition-overriding=true

    spring.servlet.multipart.file-size-threshold=100KB
    spring.servlet.multipart.max-file-size=10MB
    spring.servlet.multipart.max-request-size=10MB
    server.tomcat.max-http-post-size=10MB
    server.jetty.max-http-post-size=10MB
    spring.servlet.multipart.enabled=true

    {{- if .Values.extraConfig }}
    {{ .Values.extraConfig | indent 4 | trim }}
    {{- end }}
